# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-25 06:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_token', models.CharField(max_length=64)),
                ('last_notified_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('is_test_device', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, max_length=100)),
                ('failed', models.BooleanField(default=False)),
                ('platform', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together=set([('device_token', 'is_test_device')]),
        ),
    ]
